//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberEdit
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Member
    {
        public int MemberID { get; set; }
        public string MemberAccount { get; set; }
        public string MemberPassword { get; set; }
        public string NickName { get; set; }
        public string Email { get; set; }
        public Nullable<int> UpMemberID { get; set; }
        public byte PauseAccount { get; set; }
        public int ErrorLoginCount { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string LastLoginIp { get; set; }
        public long Exps { get; set; }
        public int MemberLevel { get; set; }
        public Nullable<int> MemberLevel2 { get; set; }
        public Nullable<int> MemberLevel3 { get; set; }
        public Nullable<int> MemberLevel4 { get; set; }
        public Nullable<int> MemberLevel5 { get; set; }
        public decimal SportsRate { get; set; }
        public decimal RealRate { get; set; }
        public decimal GameRate { get; set; }
        public decimal LotteryRate { get; set; }
        public string PicURL { get; set; }
        public byte AlarmType { get; set; }
        public long WarPoints { get; set; }
        public byte LockStatus { get; set; }
        public Nullable<decimal> EGameTuiShui { get; set; }
        public byte MemberType { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string Token { get; set; }
        public string Mobile { get; set; }
        public System.DateTime CreateTime { get; set; }
        public byte MemberComeFrom { get; set; }
    
        public virtual MemberLevels MemberLevels { get; set; }
    }
}
