//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberEdit
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLevels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberLevels()
        {
            this.A_Member = new HashSet<A_Member>();
        }
    
        public int MemberLevel { get; set; }
        public string MemberLevelDescription { get; set; }
        public decimal GameRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Member> A_Member { get; set; }
    }
}
