//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberEdit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamePlatformEntities : DbContext
    {
        public GamePlatformEntities()
            : base("name=GamePlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Admin> t_Admin { get; set; }
        public virtual DbSet<MemberLevels> MemberLevels { get; set; }
        public virtual DbSet<A_Member> A_Member { get; set; }
    }
}
